version: '3'
services:
  flask-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - MONGO_URI=mongodb+srv://admin:adminpassword@cluster0.464wvua.mongodb.net/
      - MYSQL_HOST=sqldb.cr0gumy26ddi.us-west-2.rds.amazonaws.com
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=adminpassword
      - MYSQL_DB=sqldb
    image: shaziyehtajik/myflix-app
    deploy:
      replicas: 1
