version: '3'
services:
  flask-api:
    build:
      context: .
    ports:
      - 5000:5000
    environment:
      - MONGO_URI=mongodb+srv://admin:adminpassword@cluster0.464wvua.mongodb.net/
      - MYSQL_HOST=sqldb.cr0gumy26ddi.us-west-2.rds.amazonaws.com
      - MYSQL_USER=myflix_user
      - MYSQL_PASSWORD=admin
      - MYSQL_DB=myflix_db
    image: shaziyehtajik/myflix-app
    deploy:
      replicas: 1
    secrets:
      - regcred

secrets:
  regcred:
    file:
      .dockerconfigjson
